CAR/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Cars.Queries.GetCarsList;
using Microsoft.Extensions.DependencyInjection;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Application.Common.Interfaces;
using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Application.Common.Pagination;
using Persistence;
using Microsoft.AspNetCore.Authorization;
using Application.Cars.Queries.GetCarDetail;

namespace CAR.Controllers
{
    public class CarController : Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();

        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult<CarsListVm>> GetCars(int page = 1)
        {
            var model = await Mediator.Send(new GetCarsListQuery(page,3));

            return View(model);
        }

        [AllowAnonymous]
        public async Task<ActionResult<CarDetailVm>> GetCarById(Guid id)
        {
            var vm = await Mediator.Send(new GetCarDetailQuery { Id = id });

            return base.Ok(vm);
        }
    }
}

CAR/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Rents.Commands.CreateRent;
using Microsoft.Extensions.DependencyInjection;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Application.Locations.Queries.GetLocationsListById;
using Application.CitiesLocations.Queries;
using Application.Rents.Queries.GetPersonalRentsList;
using Microsoft.AspNetCore.Mvc.Rendering;
using Application.Common.Interfaces;
using System.Runtime.CompilerServices;
using Domain.Entities;
using Application.Cities.Queries.GetCitiesList;
using Microsoft.AspNetCore.Authorization;

namespace CAR.Controllers
{
    public class RentController : Controller
    {
        private IMediator _mediator;
        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<ActionResult<CitiesListVm>> AddRent(Guid id)
        {
            var model = await Mediator.Send(new GetCitiesListQuery(id));

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult<Guid>> AddRent(CreateRentCommand command)
        {
            return await Mediator.Send(command);        
        }

        public async Task<ActionResult<PersonalRentsListVm>> GetPersonalRents()
        {
            var model = await Mediator.Send(new GetPersonalRentsListQuery());

            return View(model);
        }
    }
}

CAR/Views/Car/GetCars.cshtml
@model Application.Cars.Queries.GetCarsList.CarsListVm
@{
    ViewData["Title"] = "GetCars";
}

<div class="intro-car">
    <div class="container-fluid" id="intro">
        <div class="intro__inner" id="inner"> </div>
    </div>
    <div class="row container-fluid align-self-center align-bottom mt-5">
        <div class="col-1">

        </div>
        <div class="col-10 shadow mt-5 bg-white rounded align-self-center acc-container p-md-5 unselectable">
            @foreach (var car in Model.Cars)
            {
                if (@car.Available == true)
                {
                    <div class="row">
                        <div class="col-md-4 col-sm-12 col-xs-12">
                            <p class="text-uppercase font-weight-bold">@car.Name</p>
                            @Html.Raw("<img style='width:200px; height:120px;' src=\"data:image/jpeg;base64,"
                                                        + Convert.ToBase64String(car.Photo) + "\" />")
                        </div>
                        <div class="col-md-4 col-sm-12 col-xs-12">
                            <div class="row">
                                <div class="col-2">
                                    <div class="row">
                                        <ion-icon name="speedometer"></ion-icon>
                                    </div>
                                    <div class="row">
                                        <p class="sm-font">@car.Run</p>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="row">
                                        <ion-icon name="color-fill"></ion-icon>
                                    </div>
                                    <div class="row">
                                        <p class="sm-font">@car.TankVolume L/100km</p>
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="row">
                                        @if (@car.Conditioner == true)
                                        {
                                            <ion-icon name="snow"></ion-icon>
                                        }
                                    </div>
                                    <div class="row"></div>
                                </div>                            
                            </div>  
                            <div class="row">
                                <p>Color</p>
                                <div> : @car.Color</div>
                            </div>
                            <div class="row">
                                <p>Car Type</p>
                                <div> : @car.CarType</div>
                            </div>
                            <div class="row">
                                <p>Transmission</p>
                                <div> : @car.Transmission</div>
                            </div>                     
                        </div>
                        <div class="col-md-4 col-sm-12 col-xs-12">
                            <div class="row">
                                <table class="table table-bordered text-center">
                                    <thead>
                                        <tr>
                                            <th scope="col">from 26 days</th>
                                            <th scope="col">10-25 days</th>
                                            <th scope="col">4-9 days</th>
                                            <th scope="col">1-3 days</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>@car.Price $</td>
                                            <td>@car.PriceFourth $</td>
                                            <td>@car.PriceSecond $</td>
                                            <td>@car.PriceThird $</td>
                                        </tr>
                                    </tbody>
                                </table>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <a class="btn btn-log" value="@car.Id" asp-action="AddRent/@car.Id" asp-controller="Rent">Go</a>
                                }
                                else
                                {
                                    <a class="btn btn-log" asp-action="Login" asp-controller="Account">Go</a>
                                }
                            </div>
                        </div>
                    </div>
                    <hr />
                }
            }
            <div class="row text-right">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    @if (Model.PageViewModel.HasPreviousPage)
                    {
                        <a asp-action="GetCars"
                           asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
                           class="btn btn-log btn-width">
                            <i class=""></i>
                            Back
                        </a>
                    }
                    @if (Model.PageViewModel.HasNextPage)
                    {
                        <a asp-action="GetCars"
                           asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
                           class="btn btn-log btn-width">
                            Next
                            <i class=""></i>
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>